server:
  port: 8761
spring:
  application:
    name: cloud-eureka
  cloud:
    config:
      uri: http://localhost:8092
      fail-fast: true
      password: 123456
      username: user

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0