spring:
  application:
    name: cloud-gateway
  cloud:
    config:
      uri: http://localhost:8092
      fail-fast: true
      username: user
      password: 123456
  sleuth:
    traceId128: true
    http:
      enabled: true
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
  pattern:
    level: "[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
server:
  port: 8093