server:
  port: 8092
spring:
  profiles:
    active: test
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8091/eureka
    eureka-server-connect-timeout-seconds: 500
  instance:
    prefer-ip-address: true #采用IP进行注册
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
